### ISSUE TITLE
メイン画面作成

### ISSUE THREAD

**Issue by hideakikondo** [hideakikondo/mintgreen#2]
- メイン画面を作成する

トップ画面 (src/app/page.tsx) の実装
以下に、ワイヤーフレームを再現するための簡単なReactコンポーネントのコードと、関連するCSSの例を示します。

- ワイヤフレーム
<img width="806" alt="Image" src="https://github.com/user-attachments/assets/576228f3-296d-405f-8a40-be86a2103692" />

1. トップページコンポーネント (src/app/page.tsx)
Linkコンポーネントを使って、各パスへ遷移するようにします。

 ```TypeScript
 
import Link from 'next/link';
import styles from './page.module.css'; // 後で作成するCSSモジュールをインポート

export default function HomePage() {
  return (
    <div className={styles.container}>
      <h1 className={styles.title}>オンライン投票アプリ (Prototype)</h1>

      <div className={styles.buttonContainer}>
        {/* 選挙管理者の画面へ */}
        <Link href="/admin/elections/new" className={styles.button}>
          選挙を開催する
        </Link>

        {/* 投票画面へ */}
        <Link href="/vote" className={styles.button}>
          選挙に投票する
        </Link>

        {/* 結果画面へ */}
        <Link href="/results" className={styles.button}>
          結果を確認する
        </Link>
      </div>
    </div>
  );
}

```
2. スタイルファイル (src/app/page.module.css)
Next.jsではCSS Modulesが推奨されており、コンポーネントごとに独立したスタイルを適用できます。

```CSS

/* src/app/page.module.css */

.container {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  min-height: 100vh; /* ビューポートの高さいっぱいにする */
  background-color: #f0f0f0; /* 背景色 */
  padding: 20px;
  box-sizing: border-box; /* paddingをwidth/heightに含める */
}

.title {
  font-size: 2.5em;
  margin-bottom: 60px; /* ボタン群との間にスペース */
  color: #333;
  text-align: center;
}

.buttonContainer {
  display: flex;
  flex-direction: column;
  gap: 25px; /* ボタン間のスペース */
  width: 100%;
  max-width: 400px; /* ボタンの最大幅 */
}

.button {
  display: block; /* Linkをブロック要素にする */
  text-decoration: none; /* 下線をなくす */
  background-color: #ffffff; /* ボタンの背景色 */
  border: 1px solid #ccc; /* ボタンの枠線 */
  border-radius: 8px; /* 角丸 */
  padding: 20px 30px; /* 内側の余白 */
  font-size: 1.5em;
  color: #555;
  text-align: center;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* 影 */
  transition: all 0.3s ease; /* ホバー時のアニメーション */
  cursor: pointer;
}

.button:hover {
  border-color: #0070f3; /* ホバー時の枠線色 */
  box-shadow: 0 6px 12px rgba(0, 0, 0, 0.15); /* ホバー時の影を濃くする */
  color: #0070f3; /* ホバー時の文字色 */
  transform: translateY(-2px); /* 少し上に浮き上がるアニメーション */
}

```
実装手順
1. src/app/page.tsx の更新: 上記のTypeScript Reactコードで既存のpage.tsxファイルを置き換えます。
2. src/app/page.module.css の作成: src/appディレクトリに新しいファイルpage.module.cssを作成し、上記のCSSコードを貼り付けます。
